site_name: Quarkpulse

nav:
  - Home: index.md
  - IT for Hire: ./IT-for-hire/introductie.md
  - Dienstverlening: ./Dienstverlening/Algemeen/01-introductie.md
  - Documentatie: ./Documentatie/inleiding.md
  - FAQs: ./FAQs/introductie.md
  - Tips: ./Tips/introductie.md

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
  language: nl
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Schakel naar light mode
        tooltip: Schakel naar light mode
      primary: blue
      accent: orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Schakel naar dark mode
        tooltip: Schakel naar dark mode
      primary: blue
      accent: amber
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    annotation: material/leaf-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  homepage: https://quarkpulse.com
  analytics:
    provider: google
    property: G-XFMJKCVBVZ
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    <identifier>: <description>
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quarkpulse/
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VaRNzjrLY6d6Nm4cIo1a
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@quarkpulse

extra_css:
  - stylesheets/extra.css      

plugin:
  - tags
  - typeset
  - projects
  - optimize
  - social:
    - cache: false
  - search:
      lang: nl

markdown_extensions:
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://quarkpulse.github.io/docs/" target="_blank" rel="noopener">Quarkpulse</a>
