site_name: Quarkpulse

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: nl
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Schakel naar light mode
        tooltip: Schakel naar light mode
      primary: blue
      accent: orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Schakel naar dark mode
        tooltip: Schakel naar dark mode
      primary: blue
      accent: amber
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    annotation: material/leaf-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  analytics:
    provider: google
    property: G-XFMJKCVBVZ
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    <identifier>: <description>
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://normanvillefort.github.io/
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VaRNzjrLY6d6Nm4cIo1a
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@quarkpulse

plugin:
  - social:
    - cache: false
  - tags
  - search
  - typeset

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Quarkpulse" target="_blank" rel="noopener">Quarkpulse</a>
