site_name: Quarkpulse

nav:
  - Home: index.md
  - IT for hire:
    - Algemeen:
      - Wat is IT for hire?: wat-is.md
      - Voor wie is IT for hire?: voor-wie.md
      - IT Support: it-support.md
  - Dienstverlening:
    - Algemeen:
      - Introductie: 01-introductie.md
      - Modellen begrijpen: 02-modellen-begrijpen.md
      - Dienstmodellen: 03-dienst-modellen-hanteren.md
    - Diensten:
      - Onboarding: 10-onboarding.md
      - Quarkpulse Support: 11-quarkpulse-support.md
      - Break-en-Fix:
        - Dienstverlening: break-en-fix-dienstverlening.md
        - Onboarding: onboarding-break-fix.md
      - QMS:
        - Dienstverlening: maandelijkse-it-dienstverlening.md
        - Onboarding: onboarding-qms.md
  - Documentatie:
    - Beheer:
      - Firewall:
        - pfSense: pfsense.md
        - OpnSense: opnsense.md
      - Server:
        - Windows Server 2019: windows-server-2019.md
        - Ubuntu Linux Server 24.04: ubuntu-server-2404.md
      - Virtualisatie:
        - Proxmox VE: proxmox-ve.md
    - Cybersecurity:
      - Data Security: datasecurity.md
      - Identity and Access Management: iam.md
      - Account Security: accountsecurity.md
      - Endpoint Security: endpointsecurity.md
      - Incident Response: incident-response.md
      - Compliance and Auditing: compliance-auditing.md
      - Vendor Risk Management: vendor-risk-mngt.md
      - Physical Security: physicalsecurity.md
      - Security Awareness Training: security-awareness-training.md
    - Netwerk:
      - Kleine bedrijven: netwerk-klein.md
      - Middelgrote bedrijven: netwerk-middelgroot.md
      - Corporate: netwerk-corporate.md
    - Oplossingen:
      - On-Prem: onpremoplossingen.md
      - Cloud:
        - Opensource:
          - Authentik: authentik.md
          - Homepage Dashboard: homepage.md
          - Invoice Ninja: invoice-ninja.md
          - Mkdocs: mkdocs.md
          - Netbird: netbird.md
          - Netbox: netbox.md
          - Nginx Proxy Manager: nginx-proxy-manager.md
          - OpenProject: openproject.md
          - Proxmox: proxmox.md
          - RustDesk: rustdesk.md
          - Speedtest Tracker: speedtest-tracker.md
          - TrueNAS: truenas.md
          - UV Desk: usdesk.md
          - Wazuh: wazuh.md
          - Wireguard: wireguard.md
          - Zabbix: zabbix.md
        - Commercial:
          - Microsoft: microsoft.md
          - Amazon Webservices: aws.md
          - Alibaba Cloud: alibabacloud.md
    - Overige: overige-documentatie.md
  - FAQs:
    - Algemeen: algemene-vragen.md
    - Diensten: dienstverlening.md
    - Support: contact-support.md
  - Tips:
    - IT: it-beheer-tips.md
    - Productiviteit: productiviteit-tips.md
    - Cybersecurity: cybersecurity-bestpractices.md
    - Support: technische-support-tips.md

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
  language: nl
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Schakel naar light mode
        tooltip: Schakel naar light mode
      primary: blue
      accent: orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Schakel naar dark mode
        tooltip: Schakel naar dark mode
      primary: blue
      accent: amber
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    annotation: material/leaf-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  homepage: https://quarkpulse.com
  analytics:
    provider: google
    property: G-XFMJKCVBVZ
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    <identifier>: <description>
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quarkpulse/
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VaRNzjrLY6d6Nm4cIo1a
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@quarkpulse

extra_css:
  - stylesheets/extra.css      

plugin:
  - tags
  - typeset
  - projects
  - optimize
  - social:
    - cache: false
  - search:
      lang: nl

markdown_extensions:
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://quarkpulse.github.io/docs/" target="_blank" rel="noopener">Quarkpulse</a>
