site_name: Quarkpulse

nav:
  - Home: index.md
  - IT for hire: it-for-hire/introductie.md
    - Algemeen:
      - Wat is IT for hire?: it-for-hire/algemeen/wat-is.md
      - Voor wie is IT for hire?: it-for-hire/algemeen/voor-wie.md
      - IT Support: it-for-hire/algemeen/it-support.md
  - Dienstverlening:
    - Algemeen: dienstverlening/algemeen/01-introductie.md
      - Modellen begrijpen: dienstverlening/algemeen/02-modellen-begrijpen.md
      - Dienstmodellen: dienstverlening/algemeen/03-dienst-modellen-hanteren.md
    - Diensten:
      - Onboarding: dienstverlening/diensten/10-onboarding.md
      - Quarkpulse Support: dienstverlening/diensten/11-quarkpulse-support.md
      - Break-en-Fix:
        - Dienstverlening: dienstverlening/diensten/break-en-fix/break-en-fix-dienstverlening.md
        - Onboarding: dienstverlening/diensten/break-en-fix/onboarding-break-fix.md
      - QMS:
        - Dienstverlening: dienstverlening/diensten/qms/maandelijkse-it-dienstverlening.md
        - Onboarding: dienstverlening/diensten/qms/onboarding-qms.md
  - Documentatie: documentatie/inleiding.md
    - Beheer: documentatie/serverbeheer.md
      - Firewall: firewalls.md
        - pfSense: documentatie/firewall/pfsense.md
        - OpnSense: documentatie/firewall/opnsense.md
      - Server: servers.md
        - Windows Server 2019: documentatie/server/windows-server-2019.md
        - Ubuntu Linux Server 24.04: documentatie/server/ubuntu-server-2404.md
      - Virtualisatie: documentatie/virtualisatie/introductie.md
        - Proxmox VE: documentatie/virtualisatie/proxmox-ve.md
    - Cybersecurity: documentatie/cybersecurity.md
      - Data Security: documentatie/cybersecurity/datasecurity.md
      - Identity and Access Management: documentatie/cybersecurity/iam.md
      - Account Security: documentatie/cybersecurity/accountsecurity.md
      - Endpoint Security: documentatie/cybersecurity/endpointsecurity.md
      - Incident Response: documentatie/cybersecurity/incident-response.md
      - Compliance and Auditing: documentatie/cybersecurity/compliance-auditing.md
      - Vendor Risk Management: documentatie/cybersecurity/vendor-risk-mngt.md
      - Physical Security: documentatie/cybersecurity/physicalsecurity.md
      - Security Awareness Training: documentatie/cybersecurity/security-awareness-training.md
    - Netwerk: documentatie/netwerk/netwerkconfiguratie.md
      - Kleine bedrijven: documentatie/netwerk/netwerk-klein.md
      - Middelgrote bedrijven: documentatie/netwerk/netwerk-middelgroot.md
      - Corporate: documentatie/netwerk/netwerk-corporate.md
    - Oplossingen: documentatie/oplossingen.md
      - On-Prem: documentatie/oplossingen/onpremoplossingen.md
      - Cloud: documentatie/oplossingen/cloudoplossingen.md
        - Opensource: documentatie/oplossingen/cloud/opensource/opensource.md
          - Installatie: documentatie/oplossingen/cloud/opensource/installaties.md
            - Authentik: documentatie/oplossingen/cloud/opensource/installatie/authentik.md
            - Homepage Dashboard: documentatie/oplossingen/cloud/opensource/installatie/homepage.md
            - Invoice Ninja: documentatie/oplossingen/cloud/opensource/installatie/invoice-ninja.md
            - Mkdocs: documentatie/oplossingen/cloud/opensource/installatie/mkdocs.md
            - Netbird: documentatie/oplossingen/cloud/opensource/installatie/netbird.md
            - Netbox: documentatie/oplossingen/cloud/opensource/installatie/netbox.md
            - Nginx Proxy Manager: documentatie/oplossingen/cloud/opensource/installatie/nginx-proxy-manager.md
            - OpenProject: documentatie/oplossingen/cloud/opensource/installatie/openproject.md
            - Proxmox: documentatie/oplossingen/cloud/opensource/installatie/proxmox.md
            - RustDesk: documentatie/oplossingen/cloud/opensource/installatie/rustdesk.md
            - Speedtest Tracker: documentatie/oplossingen/cloud/opensource/installatie/speedtest-tracker.md
            - TrueNAS: documentatie/oplossingen/cloud/opensource/installatie/truenas.md
            - UV Desk: documentatie/oplossingen/cloud/opensource/installatie/usdesk.md
            - Wazuh: documentatie/oplossingen/cloud/opensource/installatie/wazuh.md
            - Wireguard: documentatie/oplossingen/cloud/opensource/installatie/wireguard.md
            - Zabbix: documentatie/oplossingen/cloud/opensource/installatie/zabbix.md
        - Commercial: documentatie/oplossingen/cloud/commercial/commercial.md
          - Microsoft: documentatie/oplossingen/cloud/commercial/microsoft.md
          - Amazon Webservices: documentatie/oplossingen/cloud/commercial/aws.md
          - Alibaba Cloud: documentatie/oplossingen/cloud/commercial/alibabacloud.md
    - Overige: documentatie/overige-documentatie.md
  - FAQs: faqs/introductie.md
    - Algemeen: faqs/algemeen/algemene-vragen.md
    - Diensten: faqs/diensten/dienstverlening.md
    - Support: faqs/support/contact-support.md
  - Tips: tips/introductie.md
    - IT: tips/it/it-beheer-tips.md
    - Productiviteit: tips/productiviteit/productiviteit-tips.md
    - Cybersecurity: tips/cybersecurity/cybersecurity-bestpractices.md
    - Support: tips/support/technische-support-tips.md

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
  language: nl
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Schakel naar light mode
        tooltip: Schakel naar light mode
      primary: blue
      accent: orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Schakel naar dark mode
        tooltip: Schakel naar dark mode
      primary: blue
      accent: amber
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    annotation: material/leaf-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  homepage: https://quarkpulse.com
  analytics:
    provider: google
    property: G-XFMJKCVBVZ
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    <identifier>: <description>
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quarkpulse/
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VaRNzjrLY6d6Nm4cIo1a
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@quarkpulse

extra_css:
  - stylesheets/extra.css      

plugin:
  - tags
  - typeset
  - projects
  - optimize
  - social:
    - cache: false
  - search:
      lang: nl

markdown_extensions:
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://quarkpulse.github.io/docs/" target="_blank" rel="noopener">Quarkpulse</a>
