site_name: Quarkpulse
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Schakel naar dark mode
      primary: blue
      accent: pink
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Schakel naar light mode
      primary: blue
      accent: orange

nav:
  - Start: index.md
  - IT for hire:
    - Introductie: it-for-hire/introductie.md
    - Wat is IT for hire?: it-for-hire/wat-is.md
    - Voor wie is IT for hire?: it-for-hire/voor-wie.md
    - IT Support: it-for-hire/it-support.md
  - Dienstverlening:
    - Introductie: dienstverlening/introductie.md
    - Wat zijn dienstverleningsmodellen?: dienstverlening/wat-zijn-modellen.md
    - Waarom Dienstverleningsmodellen gebruiken?: dienstverlening/waarom-modellen-gebruiken.md
    - Break en Fix Dienstverlening: dienstverlening/break-en-fix-dienstverlening.md
    - Maandelijkse IT Dienstverlening: dienstverlening/maandelijkse-it-dienstverlening.md
    - Onboarding proces: dienstverlening/onboarding-proces.md
    - Quarkpulse Support: dienstverlening/quarkpulse-support.md
  - Documentatie:
    - Inleiding: documentatie/inleiding.md
    - Netwerkconfiguratie: documentatie/netwerkconfiguratie.md
    - Serverbeheer: documentatie/serverbeheer.md
    - Cybersecurity: documentatie/cybersecurity.md
    - Cloudoplossingen: documentatie/cloudoplossingen.md
    - Overige documentatie: documentatie/overige-documentatie.md
  - Veelgestelde vragen:
    - Algemene vragen: veelgestelde-vragen/algemene-vragen.md
    - Dienstverlening: veelgestelde-vragen/dienstverlening.md
    - Contact en support: veelgestelde-vragen/contact-support.md
  - Tips en Best Practices:
    - IT Beheer Tips: tips/it-beheer-tips.md
    - Cybersecurity Best Practices: tips/cybersecurity-bestpractices.md
    - Productiviteit Tips: tips/productiviteit-tips.md
    - Technische Ondersteuning Tips: tips/technische-support-tips.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/normanvillefort
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Quarkpulse" target="_blank" rel="noopener">Quarkpulse</a>
