site_name: Quarkpulse

nav:
  - Home: index.md
  - IT for hire: introductie.md
    - Algemeen:
      - Wat is IT for hire?: wat-is.md
      - Voor wie is IT for hire?: voor-wie.md
      - IT Support: it-support.md
  - Dienstverlening:
    - Algemeen:
      - Introductie: 01-introductie.md
      - Modellen begrijpen: 02-modellen-begrijpen.md
      - Dienstmodellen: 03-dienst-modellen-hanteren.md
    - section: Diensten
      - Onboarding: 10-onboarding.md
      - Quarkpulse Support: 11-quarkpulse-support.md
      - Break-en-Fix:
        - Dienstverlening: break-en-fix-dienstverlening.md
        - Onboarding: onboarding-break-fix.md
      - QMS:
        - Dienstverlening: maandelijkse-it-dienstverlening.md
        - Onboarding: onboarding-qms.md
  - Documentatie: inleiding.md
    - Beheer:
      - section: Serverbeheer
        - Firewall:
          - pfSense: documentatie/beheer/firewalls/pfsense.md
          - OpnSense: documentatie/beheer/firewalls/opnsense.md
        - Server:
          - Windows Server 2019: documentatie/beheer/servers/windows-server-2019.md
          - Ubuntu Linux Server 24.04: documentatie/beheer/servers/ubuntu-server-2404.md
        - Virtualisatie:
          - Introductie: documentatie/beheer/virtualisatie/introductie.md
          - Proxmox VE: documentatie/beheer/virtualisatie/proxmox-ve.md
    - Cybersecurity:
      - Data Security: documentatie/cybersecurity/datasecurity.md
      - Identity and Access Management: documentatie/cybersecurity/iam.md
      - Account Security: documentatie/cybersecurity/accountsecurity.md
      - Endpoint Security: documentatie/cybersecurity/endpointsecurity.md
      - Incident Response: documentatie/cybersecurity/incident-response.md
      - Compliance and Auditing: documentatie/cybersecurity/compliance-auditing.md
      - Vendor Risk Management: documentatie/cybersecurity/vendor-risk-mngt.md
      - Physical Security: documentatie/cybersecurity/physicalsecurity.md
      - Security Awareness Training: documentatie/cybersecurity/security-awareness-training.md
    - Netwerk:
      - Netwerkconfiguratie:
        - Kleine bedrijven: documentatie/netwerk/netwerk-klein.md
        - Middelgrote bedrijven: documentatie/netwerk/netwerk-middelgroot.md
        - Corporate: documentatie/netwerk/netwerk-corporate.md
    - Oplossingen:
      - On-Prem: documentatie/oplossingen/onpremoplossingen.md
      - Cloud:
        - Opensource:
          - section: Installatie
            - Authentik: documentatie/oplossingen/cloud/opensource/installaties/authentik.md
            - Homepage Dashboard: documentatie/oplossingen/cloud/opensource/installaties/homepage.md
            - Invoice Ninja: documentatie/oplossingen/cloud/opensource/installaties/invoice-ninja.md
            - Mkdocs: documentatie/oplossingen/cloud/opensource/installaties/mkdocs.md
            - Netbird: documentatie/oplossingen/cloud/opensource/installaties/netbird.md
            - Netbox: documentatie/oplossingen/cloud/opensource/installaties/netbox.md
            - Nginx Proxy Manager: documentatie/oplossingen/cloud/opensource/installaties/nginx-proxy-manager.md
            - OpenProject: documentatie/oplossingen/cloud/opensource/installaties/openproject.md
            - Proxmox: documentatie/oplossingen/cloud/opensource/installaties/proxmox.md
            - RustDesk: documentatie/oplossingen/cloud/opensource/installaties/rustdesk.md
            - Speedtest Tracker: documentatie/oplossingen/cloud/opensource/installaties/speedtest-tracker.md
            - TrueNAS: documentatie/oplossingen/cloud/opensource/installaties/truenas.md
            - UV Desk: documentatie/oplossingen/cloud/opensource/installaties/usdesk.md
            - Wazuh: documentatie/oplossingen/cloud/opensource/installaties/wazuh.md
            - Wireguard: documentatie/oplossingen/cloud/opensource/installaties/wireguard.md
            - Zabbix: documentatie/oplossingen/cloud/opensource/installaties/zabbix.md
          - Commercial:
            - Microsoft: documentatie/oplossingen/cloud/commercial/microsoft.md
            - Amazon Webservices: documentatie/oplossingen/cloud/commercial/aws.md
            - Alibaba Cloud: documentatie/oplossingen/cloud/commercial/alibabacloud.md
    - Overige:
      - Overige documentatie: documentatie/overige-documentatie.md
  - FAQs: introductie.md
    - Algemeen:
      - Algemene vragen: faqs/algemene-vragen.md
    - Diensten:
      - Dienstverlening: faqs/dienstverlening.md
    - Support:
      - Contact Support: faqs/contact-support.md
  - Tips: introductie.md
    - IT:
      - IT Beheer tips: tips/it-beheer-tips.md
    - Productiviteit:
      - Productiviteit tips: tips/productiviteit-tips.md
    - Cybersecurity:
      - Cybersecurity best practices: tips/cybersecurity-bestpractices.md
    - Support:
      - Technische support tips: tips/technische-support-tips.md

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    - toc.follow
    #- toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips
  language: nl
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Schakel naar light mode
        tooltip: Schakel naar light mode
      primary: blue
      accent: orange
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Schakel naar dark mode
        tooltip: Schakel naar dark mode
      primary: blue
      accent: amber
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    annotation: material/leaf-circle
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra:
  homepage: https://quarkpulse.com
  analytics:
    provider: google
    property: G-XFMJKCVBVZ
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  status:
    <identifier>: <description>
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quarkpulse/
    - icon: fontawesome/brands/whatsapp
      link: https://whatsapp.com/channel/0029VaRNzjrLY6d6Nm4cIo1a
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@quarkpulse

extra_css:
  - stylesheets/extra.css      

plugin:
  - tags
  - typeset
  - projects
  - optimize
  - social:
    - cache: false
  - search:
      lang: nl

markdown_extensions:
  - def_list
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://quarkpulse.github.io/docs/" target="_blank" rel="noopener">Quarkpulse</a>
