site_name: Quarkpulse
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: nl
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Schakel naar dark mode
      primary: blue
      accent: pink
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Schakel naar light mode
      primary: blue
      accent: orange

nav:
  - 'Start': 'index.md'
  - 'IT for hire':
    - 'Introductie': 'IT for hire/introductie.md'
    - 'Wat is IT for hire?': 'IT for hire/wat-is.md'
    - 'Voor wie is IT for hire?': 'IT for hire/voor-wie.md'
    - 'IT Support': 'IT for hire/it-support.md'
  - 'Dienstverlening':
    - 'Introductie': 'Dienstverlening/introductie.md'
    - 'Wat zijn dienstverleningsmodellen?': 'Dienstverlening/wat-zijn-modellen.md'
    - 'Waarom Dienstverleningsmodellen gebruiken?': 'Dienstverlening/waarom-modellen-gebruiken.md'
    - 'Break en Fix Dienstverlening': 'Dienstverlening/break-en-fix-dienstverlening.md'
    - 'Maandelijkse IT Dienstverlening': 'Dienstverlening/maandelijkse-it-dienstverlening.md'
    - 'Onboarding proces': 'Dienstverlening/onboarding-proces.md'
    - 'Quarkpulse Support': 'Dienstverlening/quarkpulse-support.md'
  - 'Documentatie':
    - 'Inleiding': 'Documentatie/inleiding.md'
    - 'Netwerkconfiguratie': 'Documentatie/netwerkconfiguratie.md'
    - 'Serverbeheer': 'Documentatie/serverbeheer.md'
    - 'Cybersecurity': 'Documentatie/cybersecurity.md'
    - 'Cloudoplossingen': 'Documentatie/cloudoplossingen.md'
    - 'Overige documentatie': 'Documentatie/overige-documentatie.md'
  - 'Veelgestelde vragen':
    - 'Introductie': 'Veelgestelde vragen/introductie.md'
    - 'Algemene vragen': 'Veelgestelde vragen/algemene-vragen.md'
    - 'Dienstverlening': 'Veelgestelde vragen/dienstverlening.md'
    - 'Contact en support': 'Veelgestelde vragen/contact-support.md'
  - 'Tips en Best Practices':
    - 'Introductie': 'Tips & Best Practices/introductie.md'
    - 'IT Beheer Tips': 'Tips & Best Practices/it-beheer-tips.md'
    - 'Cybersecurity Best Practices': 'Tips & Best Practices/cybersecurity-bestpractices.md'
    - 'Productiviteit Tips': 'Tips & Best Practices/productiviteit-tips.md'
    - 'Technische Ondersteuning Tips': 'Tips & Best Practices/technische-support-tips.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/normanvillefort
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/quarkpulse
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quarkpulse/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Quarkpulse" target="_blank" rel="noopener">Quarkpulse</a>
